Service
Hargeon/parentheses pull request #2
Opened 2021-09-07 18:55 UTC by Hargeon

# Tasks

- [x] Add service that generates a random sequence of parentheses
- [x] Add tests

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2021-09-10 11:22 UTC, gordonBusyman requested changes

2021-09-10 11:22 UTC, gordonBusyman commented on cmd/main.go
> +func main() {
1. Move main to `/cmd/{pkg name}/main.go`
2. Add basic graceful shutdown (ex. [here](https://medium.com/honestbee-tw-engineer/gracefully-shutdown-in-go-http-server-5f5e6b83da5a))

2021-09-10 13:58 UTC, Hargeon commented on cmd/main.go
> +func main() {
Done

2021-09-12 09:03 UTC, gordonBusyman approved these changes

2021-09-12 09:27 UTC, merged